### ISSUE TITLE
mining GRAFT issues.

### ISSUE THREAD

**Issue by javietanh** [Bendr0id/xmrigCC#121]
Hi guys,

I mine graft at https://graft.hashvault.pro and all of my miner working fine but only once miner had this problem: 
- miner submit hash to pool
- xmrigcc server console report hashrate submit.
But on the pool i can't see that worker. no error no problem, can't find out why?

**Comment by Bendr0id** [comment]
Thats possible. Lot of times the pool dashboard has a delay. Nothing to worry ablut, when the hashes are accepted on the pool it will appear after a while.

But keep in mind, not the hashrate is rewarded by the pool only the submitted shares. when the diff is very high, it will take a lot of time until it a valid share is found. Maybe try to use a port with lower diff.

But this is not a miner issue at all.
 I'll close this ticket.


Am 31.05.2018 12:33 schrieb Nguyễn Việt Anh <notifications@github.com>:

Hi guys,

I mine graft at https://graft.hashvault.pro and all of my miner working fine but only once miner had this problem:

  *   miner submit hash to pool
  *   xmrigcc server console report hashrate submit.
But on the pool i can't see that worker. no error no problem, can't find out why?

**Comment by javietanh** [comment]
I mine about an hours but still can't see the worker on dashboard

Get Outlook for Android

________________________________

**Comment by Bendr0id** [comment]
Just tested GRAFT on the same pool. Works for me.

1. Make sure you set the right wallet id
2. Check how high the diff is
3. Check the XMRigCC dashboard for "Shares Good" and "Shares Total"

**Comment by javietanh** [comment]
Guys, what I found that the took running with pow 0. It's should be pow 1 actually. Don't know how to force it running with pow 1

Get Outlook for Android

________________________________

**Comment by javietanh** [comment]
![image](https://user-images.githubusercontent.com/5907838/40782963-28f0fb40-650b-11e8-8c06-ad955e32ffe3.png)

**Comment by djfinch** [comment]
https://github.com/Bendr0id/xmrigCC/blob/master/src/config.json#L7

**Comment by javietanh** [comment]
this is my config 
![image](https://user-images.githubusercontent.com/5907838/40783177-ddcb1546-650b-11e8-96aa-a1a63fc1e754.png)
i try with any other options but it's not changing.

**Comment by Bendr0id** [comment]
you should read the coin config documentation..

https://github.com/Bendr0id/xmrigCC/wiki/Coin-configurations#graft-grft

**Comment by javietanh** [comment]
Awww crazy. Others miner working only this miner stucked. Same config, same version. Only this worker happen


Get Outlook for Android

________________________________

**Comment by Bendr0id** [comment]
I cant see a problem. You're hashes seem to be accepted by the pool, otherwise there would be a big red "REJECTED" line.

**Comment by javietanh** [comment]
no error reported, all hashes accepted by the pool but can't see it on the dashboard and check with the pool api -> null. can't understand what the heck is going on. only this pool and this worker, if i change to other pool like https://cryptoknight.cc/graft the worker work fine (pow 1) but with hashvault this worker report (pow 0)

Can't change the pow of this worker even i force with "pow-variant": "1" but still not work.

**Comment by Bendr0id** [comment]
PoW can be overwritten by pool/proxy. That's why maybe you're config in this case is not used. Just for testing, can you maybe change the worker-id (pass) maybe hashvault has something connected to the worker. Maybe it's blocked?! I don't know. Very strange behavior, please ask him in the chat, he is always willing to help.

Am 01.06.2018 14:19 schrieb Nguyễn Việt Anh <notifications@github.com>:

no error reported, all hashes accepted by the pool but can't see it on the dashboard and check with the pool api -> null. can't understand what the heck is going on. only this pool and this worker, if i change to other pool like https://cryptoknight.cc/graft the worker work fine (pow 1) but with hashvault this worker report (pow 0)

Can't change the pow of this worker even i force with "pow-variant": "1" but still not work.

**Comment by javietanh** [comment]
strange, i just test with all of the mining software, xmrig, xmr-stak and other one, all of them have same problem like this.

**Comment by Bendr0id** [comment]
Ask hashvault, maybe this ip is banned/blocked for whatever reason.

Am 01.06.2018 14:40 schrieb Nguyễn Việt Anh <notifications@github.com>:

strange, i just test with all of the mining software, xmrig, xmr-stak and other one, all of them have same problem like this.

**Comment by Bendr0id** [comment]
Or someone else is overwriting the DNS and forwarding to another pool. Please try with ip of the pool only.

Am 01.06.2018 15:10 schrieb Ben Gräf <ben@graef.in>:
Ask hashvault, maybe this ip is banned/blocked for whatever reason.

Am 01.06.2018 14:40 schrieb Nguyễn Việt Anh <notifications@github.com>:

strange, i just test with all of the mining software, xmrig, xmr-stak and other one, all of them have same problem like this.

**Comment by javietanh** [comment]
![image](https://user-images.githubusercontent.com/5907838/40849559-71aefdfa-65ec-11e8-98ea-867e749eec1b.png)

check it out: i try to run the proxy on same machine of the miner and the proxy report in the picture. when i run the proxy on other machine and point the url of the miner to the proxy everything working fine. what is the problem here?

**Comment by Bendr0id** [comment]
Man someone if modifying your traffic and forwarding out to his own pool! Otherwise is can't explain it. Try with the IP of graft pool instead of the domain. I'll close this ticket now. Doesn't seem to be miner issue

Am 01.06.2018 17:39 schrieb Nguyễn Việt Anh <notifications@github.com>:

[image]<https://user-images.githubusercontent.com/5907838/40849559-71aefdfa-65ec-11e8-98ea-867e749eec1b.png>

check it out: i try to run the proxy on same machine of the miner and the proxy report in the picture. when i run the proxy on other machine and point the url of the miner to the proxy everything working fine. what is the problem here?

**Comment by djfinch** [comment]
@javietanh please run ```nslookup pool.graft.hashvault.pro``` and post the result here.

**Comment by javietanh** [comment]
here we go:
![image](https://user-images.githubusercontent.com/5907838/40852927-5d8a57d4-65f6-11e8-9f39-d234d3efe46e.png)

**Comment by djfinch** [comment]
Try to add dot at the end query so it's ```nslookup pool.graft.hashvault.pro.``` but I think it's definitively something on your side... You can see one of their IP on below screenshot so use it for test but not for regular run as this is GeoIP based on my location (Central Europe).
 
![image](https://user-images.githubusercontent.com/13107713/40853153-55c98520-65cd-11e8-9fa4-4655f654ea34.png)

**Comment by javietanh** [comment]
Thanks i will try

Get Outlook for Android

________________________________

**Comment by Bendr0id** [comment]
Any new outcome here? Can i close the ticket?
