### ISSUE TITLE
1.6.5 Miner memory leak

### ISSUE THREAD

**Issue by uz-spark** [Bendr0id/xmrigCC#142]
Just noticed that miner on one of my machines chewed-up 3.65 GB of private memory, looks like ML. Is there way i can help to track that ?

Setup is Windows 10 LTSB x64 on VMWare ESXi with 2x12 core xeon CPUs, miner is in custom core affinity configuration (0xEAAEAA).

**Comment by Bendr0id** [comment]
Thanks for reporting this.

I need some more infors. Which os? Is it going on a single machine or on more machines?

Are you sure that it is 1.6.5? Because there was a memory leak in the previous version.

For now the best is to just restart the miner via dashboard. I'll start investigating later today.

Am 30.06.2018 12:51 schrieb uz-spark <notifications@github.com>:

Just noticed that miner on one of my machines chewed-up 3.65 GB of private memory, looks like ML. Is there way i can help to track that ?

**Comment by uz-spark** [comment]
I've mentioned my setup in the first post. Yes that's 1.6.5
`[2018-06-29 15:26:43] cryptonight hash self-test
[2018-06-29 15:26:44] cryptonight hash self-test... successful.
[2018-06-29 15:26:44]  * VERSIONS:     XMRigCC/1.6.5 (based on XMRig) libuv/1.14.1 gcc/7.3.0 (RELEASE with TLS)
[2018-06-29 15:26:44]  * CPU:          Intel(R) Xeon(R) CPU E5-2420 v2 @ 2.20GHz (2) x64 AES-NI
[2018-06-29 15:26:44]  * CPU L2/L3:    12.0 MB/30.0 MB
[2018-06-29 15:26:44]  * THREADS:      14, cryptonight, aes=1, hf=1, donate=1%, affinity=0xEAAEAA`

I have another Xeon server on ESXi and there's no ML, but core affinity config there's 0xAAAA. And several consumer PCs with active miners (and threads auto-config) aren't showing signs of MLs too. So i suspect there's smth wrong to do with 0xEAAEAA core config.

**Comment by Bendr0id** [comment]
As you can see, when i received the mail, it doesnt contain a config. 

Anyways, i checked all my miners and they have a constant memory usage right now. Is the memory on that one machine growing or is it just high? I also started valgrind, but it didn't found a leak so far.

**Comment by uz-spark** [comment]
It's steadily growing, miner is online for 20.5 hours now, private memory is 4.2 GB, only on that particular machine, i'll try to set plain 0xAAAAAA core affinity to see if it will change something.

**Comment by uz-spark** [comment]
I restarted another server today and there were leak too after restart, i'm out of ideas now. Reconfigured guest to use only physical cores in ESXi to get rid of affinity completely, seems to work for now, will see tomorrow.

**Comment by Bendr0id** [comment]
Hmm.. Hard for me to debug and even harder to understand what it could have todo with the affinity.
The whole part doesn't contain a single malloc/new.

Does the process at some point die because of the memory leak, or will it just start freeing up some stuff..? That could be related to page locking, but that wouldn't be a problem, because it always frees the memory when someone else needs it.

**Comment by Bendr0id** [comment]
I just had some idea..

Is this miner having a "huge" number set for  `"remote-logging-max-rows"`?

That would explain the growing  and high memory usage..

**Comment by Bendr0id** [comment]
Any more info here?
