### ISSUE TITLE
Dashboard (Please configure a Dashboard) weirdness

### ISSUE THREAD

**Issue by tknecht** [Bendr0id/xmrigCC#20]
Hi,

working on an alpine docker container for the CC Server and ending up in total weirdness.

Container starts, everything looks good. 

```
12/31/2017 1:27:01 AM * VERSIONS:     XMRigCC/1.3.0 (based on XMRig 2.4.3) libuv/1.11.0 gcc/6.3.0
12/31/2017 1:27:01 AM * COMMANDS:     quit
12/31/2017 1:27:01 AM[2017-12-31 00:27:01] XMRigCC Server started on Port: 4444
``` 

When opening in a browser I get a login request, which passes and than I end up on "Please configure a Dashboard". I have seen that index.html needs to be in the same folder as binary. So I took care of this:

```
~/xmrigccserver # ls -la
total 1356
drwxr-xr-x    2 root     root          4096 Dec 31 00:15 .
drwx------    5 root     root          4096 Dec 31 00:15 ..
-rw-r--r--    1 root     root           311 Dec 31 00:15 config_cc.json
-rw-r--r--    1 root     root         28194 Dec 30 23:57 index.html
-rwxr-xr-x    1 root     root       1341744 Dec 30 23:57 xmrigCCServer
```

Whatever I tried I can't get it up and running. 
Is there maybe a hidden and a bit more outspoken verbose mode, that can be helpful?

Thanks

**Comment by tknecht** [comment]
Holy Crap. 2:30 am and I stumble upon a solution. 
Not sure it's a good one, but it works. 

Tell that thing "custom-dashboard" : "/root/xmrigccserver/index.html" in the config file.

It feels ugly and dirty, so I you somebody has a better way, please let me know.

Thanks

**Comment by Bendr0id** [comment]
Hi Tobias,

I think it's just that XMRigCC somehow is not able to detect the oath where it runs. I think you are starting the server from a different folder like /#: ./root/xmrigccserver/xmrigCCServer

For this case it's normal that you have to provide the full path to the config and or dashboard. So that isn't a bad solution it's a good one.

Thanks for sharing your work. I appreciate if you put it to the wiki. There is already a part about docker.

**Comment by d13g0s0uz4** [comment]
if you change the path for logs and/or to config file you should specif the full path to index.html.
is it normal?
