### ISSUE TITLE
WebSocket Implementation/Support

### ISSUE THREAD

**Issue by hetmann** [Bendr0id/xmrigCC#22]
Hi @Bendr0id 
Very nice implementation of the CC server.

I do have a suggestion:
- [ ] **web-socket server/client** would improve the CC `usability` using a SPA app

**Comment by Bendr0id** [comment]
Good idea, but I'm not that deep into webdev. In other words I don't have a clue what is needed Todo that. What would be the the benefit of doing that? Push of data instead of polling? Better notifications? Something else?

**Comment by hetmann** [comment]
@Bendr0id thanks for the reply.
The idea of a web-socket server is that when a miner connects to a server it creates a bidirectional data stream and an event emitting system.

The benefits are multiple, e.q.:
- live stats by pushing the hashes to the server
- live status of the miners (disconnecting/reconnecting or OS stats)
- no web routing (the implementation is based on events)

Anyways, I was searching for something similar to implement in my miners and I found your project.

**Comment by monerorus** [comment]
It make sence in connection between dashboard and server i think. Web-socket is for web.
In connections between miner and server need something like zeromq maybe.

**Comment by untoreh** [comment]
this is just imho..
I can see how websockets can offer better monitoring from the dashboard, at the same time it seems to be kinda low priority since the main purpose of xmrigCC is to command and control? 
Also I don't see the immediate benefit of a faster message protocol between the server and the miner, unless you are pushing configs every second or so? which seems silly to me since you wouldn't have enough data to make meaningful decisions...overall I don't see it as a bottleneck as it would be between miners and pools
