### ISSUE TITLE
Loki fork

### ISSUE THREAD

**Issue by Miner1305** [Bendr0id/xmrigCC#255]
Hi
does our miner support randomxl algorithm
loki is forking tomorrow 24thjuly.

https://loki.network/2019/06/27/lokis-hashing-algorithm-change/

**Comment by Bendr0id** [comment]
Not implemented so far

**Comment by Miner1305** [comment]
any plans to implement this ?

**Comment by Bendr0id** [comment]
Maybe since i'm currently preparing stuff for randomX. Would be helpful if there is a working miner for loki (randomXL) but can't find one.

**Comment by Miner1305** [comment]
any update regarding the randomxl

**Comment by Bendr0id** [comment]
No. I'm on vacation. Will start looking into it next week. But don't expect to be rdy on Monday.

Am 26.07.2019 13:05 schrieb Miner1305 <notifications@github.com>:

any update regarding the randomxl

**Comment by Miner1305** [comment]
happy holidays

**Comment by Miner1305** [comment]
Hi, any update.

**Comment by bobbieltd** [comment]
+1 waiting for randomX (XMR/LOK). Thanks for great app.

**Comment by Julio-K** [comment]
new updates?

**Comment by Bendr0id** [comment]
I'm on it but it takes some time. Need todo some refactoring and busy with real life

**Comment by Bendr0id** [comment]
Full rebase of xmrig 3.0 is almost done. Looking for beta testers

**Comment by uz-spark** [comment]
Count me in.

**Comment by Julio-K** [comment]
me too!

**Comment by Miner1305** [comment]
i'm in

**Comment by djfinch** [comment]
@Bendr0id #meetoo :) As usual : Deb/Ubu, Win7/10, macOS10.11.6+ ;)

**Comment by bobbieltd** [comment]
#upupup #hottag #thankbendroid #howtojoin

**Comment by Bendr0id** [comment]
https://github.com/Bendr0id/xmrigCC/releases/tag/2.0.0-beta1

Please report any issues

**Comment by Miner1305** [comment]
can you share the config file for loki, i am not able to mine it.

**Comment by Bendr0id** [comment]
just use the one which is provided and only add your wallet and server. The miner will autogenerate a suitable config for you

**Comment by uz-spark** [comment]
Also specify pool algorithm, some pools don't support auto negotiation.

**Comment by Bendr0id** [comment]
oh yeah, put "rx/loki" there

**Comment by bobbieltd** [comment]
Why is this thread for testers closed ?
I runned into same issue with xmrig upstream when pool was restarted https://github.com/xmrig/xmrig/issues/1138 with argon2/chukwa (xmrigCC v2 beta, linux, compiled from source, Ubuntu 18)

On pool's side, xmrigCC client keeps trying to login (new login) and pools send OK with job (but no shares submitted anymore).
On client's side's logs after "no active pools, stop mining", there are only n/a n/a n/a
It happens when I put "argon2/chukwa" for algo negotiation. I temporarily remove algo negotiation for now (without negotiation, restarting pool does not cause stopped mining at miners' side anymore)

**Comment by Bendr0id** [comment]
@bobbieltd should be fixed on the evolved branch. if not please create a separate ticket.

**Comment by bobbieltd** [comment]
Great ! Thanks a lot for your super software.
