### ISSUE TITLE
[work-around] Linux usb-live with xmrigCC

### ISSUE THREAD

**Issue by MrCook1es** [Bendr0id/xmrigCC#330]
I would like to create a bootable USB stick, with xmrigCC installed in auto boot. So as not to install anything on the PC and not to compromise its data.
With wintousb and an external USB SSD, I had a fully functional windows 10 live.
But I would like to do the same thing using the lightest of compatible usb-linux distribution with xmrigCC .
Which linux distribution do you recommend?

**Comment by djfinch** [comment]
Try Alpine. Do not forget to make it static to avoid installing libraries there...

**Comment by MrCook1es** [comment]
> 
> 
> Try Alpine. Do not forget to make it static to avoid installing libraries there...
> 
> **EDIT:**
> Static version will not work. I forgot that Alpine using musl / libc so you have to install dependencies and compile miner from scratch... But I was able to make it work in testing docker container...
> 
> ![Screenshot 2020-12-18 at 14 17 37](https://user-images.githubusercontent.com/13107713/102618888-d5285c00-413b-11eb-9632-ada84bde8e75.jpg)

thaks for your reply!
so if I understand correctly, I can install docker container and then start it from there? without having to compile the miner?

**Comment by djfinch** [comment]
Hello,

Nope, I mean you can make it work on Alpine linux, too. Alpine Linux is minimalistic distribution useful for simple task. However, it using musl/libc instead of glibc so pre-compiled xmrigCC does not work. So you have to install [Alpine Linux on USB](https://wiki.alpinelinux.org/wiki/Create_a_Bootable_USB), enable 'edge' (for ssl and libuv) and 'testing' (for hwloc) repositories, install requirements for compilation and compile xmrigCC there. Then you should get working bootable linux with xmrigCC inside. I've used docker container to test if compilation works & skip installing and booting from USB.

Please do not forget that build dependencies / libraries have different names in Alpine:
build-essential --> build-base
libuv1-dev --> libuv-dev
libssl-dev --> libressl-dev
libhwloc-dev --> hwloc-dev

## Or you can use distro which using glibc (ubuntu, debian, whatever).

**Comment by Bendr0id** [comment]
I have a tiny ArchBang linux live usb-stick which immediately starts the miner after boot. 
It uses my static linux binaries which don't have any dependencies.
No docker needed in this case.

You only need to boot the stick once in persistent mode, download the miner, create an autostart for it with a smal delay to make sure wifi/network is connected. 

Then just plug it in somewhere and it will start mining.

**Comment by Bendr0id** [comment]
XUbuntu / LUbuntu are light weight too and do support the same^. For beginners it might be easier than Arch*.

**Comment by Bendr0id** [comment]
Can this be closed?

**Comment by MrCook1es** [comment]
yes, thanks!
I solved with XUbuntu. Perfect!
