### ISSUE TITLE
Allow update of program from CC server

### ISSUE THREAD

**Issue by rekonnected** [Bendr0id/xmrigCC#4]
It would be a pain for a lot of miners, since you'd have to manually update each one and restart it. If you can update the config remotely, why not add a config switch that allows the exe to be updated on a restart?

**Comment by Bendr0id** [comment]
Good point, but it's not that easy to override an an running exe file. Additional virus scanners wouldn't be happy with that. And the xmrigCCServer server would have to know which binary to deploy. Could also be a Linux miner. But I'll keep that in mind an think about a suitable solution.

**Comment by rekonnected** [comment]
In response to the running EXE problem, you could use a solution mentioned like here (https://social.msdn.microsoft.com/Forums/vstudio/en-US/c9a95e66-58a3-49b0-9474-92a46dbe252c/how-to-download-and-replace-running-exe?forum=vbgeneral), which suggests using another program to download and subsequently run the new file. Since the CC server checks for updates, you could likely include something in the program that reports miner version back to the CC server, allowing remote update.

In the Miner/Daemon, you would have to add a new function which, on command reciept from the CC server, starts the updater program (which likely waits a few seconds), stops itself, and then once the updater program has completed the download and replacement, starts the newly downloaded program with existing configuration.

**Comment by Bendr0id** [comment]
Will have a look..

**Comment by rekonnected** [comment]
I've come up with a possible scheme for updating both miner and daemon. I've graphed it out for ya here.
![xmrig update](https://user-images.githubusercontent.com/31298266/34140805-2e1e0b6c-e44b-11e7-8eba-5af3847d5f50.jpg)

**Comment by MattBushey** [comment]
+1, have been testing this on a smaller amount of boxes, and tonight could see the troubles of keeping up.  Not that that is a new problem that was created, however there is a new solution that has been proposed :) With the daemon running the file, leave that running nuke the file, replace and fire at will. 

One way that may be a bit "safer" as allows a fall back is by creating a secondary file name instead of trying to overwrite the other right off the hop and running that first.,  
ie;
OGMiner.exe
and
DownloadedFresh.exe 

Daemon runs OGMiner.exe from way back in the day its time to retire so it downloads DownloadedFresh.exe,   Daemon runs DownloadedFresh.exe at that point terminating OGMiner.exe, on successful load of DownloadedFresh.exe it then copies over top of OGMiner.exe  and runs that terminating its self,  OGMiner.exe starts and deletes DownloadedFresh.exe on startup. 

That would allow for a fall back scenario should anything fail, bad download etc.   Since at times CPU will be cranked downloads can often go weird.

Hope that makes sense. 

Cheers

**Comment by enricodias** [comment]
I've worked on a desktop app that automatically update itself and we had no issues with anti viruses, but the app was installed in the appdata folder on windows.

Another program (the updater) checks for a new version every few minutes in the background. When a new version is available, the server sends a link of a zip file containing the update. The updater downloads and unzip the zip contents in a temp folder, stops the app and moves the files from the temp folder to the app folder replacing existing files.

There are a few more things in our updater, like checking if the app is not doing anything important before stopping it, but I don't think this is needed here.
