### ISSUE TITLE
No Auto Creation of config.json by the Client

### ISSUE THREAD

**Issue by MarQuisKnox** [Bendr0id/xmrigCC#42]
The client (xmrigDaemon) does not automatically create `config.json` if running from the command line w/ parameters. This results in not being able to edit the configuration of the client on the server.

Is this the expected behavior?

Client Error:

````
[2018-02-17 17:48:25] [CC-Client] Command: PUBLISH_CONFIG received -> publish config
[2018-02-17 17:48:25] Not able to load client config /.download/xmrigCC/config.json. Please make sure it exists!
````

Server Error:

````
Unable to fetch config.json - Please make sure that you pulled the config before!
````

**Comment by Bendr0id** [comment]
Yes this is expected behavior. Just put a default_confog.json to the server. That one you can modify for each miner via dashboard and push to the miner. Keep in mind, commandline parameters overrule the config file. So if you want to start without config, start the miner only with cc-url and cc-authtoken, rest can be changed via config remotely.

Am 17.02.2018 17:52 schrieb MarQuis Knox <notifications@github.com>:

The client (xmrigDaemon) does not automatically create config.jsonif running from the command line w/ parameters. This results in not being able to edit the configuration of the client on the server.

Is this the expected behavior?

Client Error:

[2018-02-17 17:48:25] [CC-Client] Command: PUBLISH_CONFIG received -> publish config
[2018-02-17 17:48:25] Not able to load client config /.download/xmrigCC/config.json. Please make sure it exists!


Server Error:

Unable to fetch config.json - Please make sure that you pulled the config before!

**Comment by MarQuisKnox** [comment]
Thanks for your prompt response. 

Where should `default_config.json` exist for the server? From reading the docs it seems by default it uses the working directory?

Also, did you consider applying this remote config logic to xmr-stak or xmrig-nvidia?

**Comment by Bendr0id** [comment]
Jeah just put it in the working directory.

Once I'm finished with TLS/SSL support I'll start integrating CC feature into xmrig-nvidia and xmrig-amd.

Am 17.02.2018 18:04 schrieb MarQuis Knox <notifications@github.com>:

Thanks for your prompt response.

Where should default_config.json exist for the server? From reading the docs it seems by default it uses the working directory?

Also, did you consider applying this remote config logic to xmr-stak or xmrig-nvidia?

**Comment by MarQuisKnox** [comment]
Thanks!
