### ISSUE TITLE
CC server and html webpage question

### ISSUE THREAD

**Issue by Zelecktor** [Bendr0id/xmrigCC#45]
It is possible to host CC server on a VPS and the html webpage in another hosting service?

I see that the webpage doesnt have a conection server script (I suppose that by default it searchs the server at localhost).

Just because i have a VPS and a web service (which it has a domain, cpanel and ssl certificate). But i cant link my domain with my VPS.

**Comment by Bendr0id** [comment]
I think it's without major code changes not possible to do this. But anyways, next release of XMRigCC will support TLS/SSL, where you can set your cert.

Am 23.02.2018 00:58 schrieb Zelecktor <notifications@github.com>:

It is possible to host CC server on a VPS and the html webpage in another hosting service?

I see that the webpage doesnt have a conection server script (I suppose that by default it searchs the server at localhost).

Just because i have a VPS and a web service (which it has a domain, cpanel and ssl certificate). But my domain i cant link with my VPS.

**Comment by Zelecktor** [comment]
Thanks for the answer!
Yes, already i could compile CC server, and host the web in the same VPS. works perfectly.
Got issues in compile the rest, see #46
