### ISSUE TITLE
Add delay to ControlCommand

### ISSUE THREAD

**Issue by Zelecktor** [Bendr0id/xmrigCC#51]
Im not expert in the matter but i have been searching for hours the control command script.
Im using a third party script to pause xmrigMiner.exe (not from the CC server) but after do it, CC-client try to re-start mining with the command every 10 seconds.

![captura](https://user-images.githubusercontent.com/19712343/36695410-0307d3c0-1b20-11e8-8e74-1fa99e1a5715.PNG)

My solution is to add more time delay (1minute) or ignore command from the CC-client.
Thanks in advance

**Comment by Bendr0id** [comment]
I think you are misunderstanding the whole product. Can't see any problem or misbehavior. The main purpose of the server is to deliver ever, then seconds a command to the miner. If a third party script is used to overwrite these settings or change the behavior, the whole product doesn't make sense.

Am 26.02.2018 22:09 schrieb Zelecktor <notifications@github.com>:

Im not expert in the matter but i have been searching for hours the control command script.
Im using a third party script to pause xmrigMiner.exe (not from the CC server) but after do it, CC-client try to re-start mining with the command every 10 seconds.

[captura]<https://user-images.githubusercontent.com/19712343/36695410-0307d3c0-1b20-11e8-8e74-1fa99e1a5715.PNG>

My solution is to add more time delay (1minute) or ignore command from the CC-client.
Thanks in advance

**Comment by Zelecktor** [comment]
Here's is the case. If I oppen a software that demands my CPU (listed on my script), the script pause the miner (automatically), and resume when i close the software (video games, for example). But as you see on the image, CC-client try to resume.

It is like pause-resume-pause-resume-pause-resume every 10 seconds. Experimenting lag, fps drops, etc.

**Comment by kensagle** [comment]
Have you tried to set the CPU priority to 0 and/or max CPU usage to something lower than 100.  You should not have to pause if the priority is low.

**Comment by Zelecktor** [comment]
yes, i tried but the ideal is to pause for gamming. If you want i can upload my script.

**Comment by untoreh** [comment]
@kensagle @Zelecktor  afaik the cpu usage setting is only to limit the number of threads when the threads are chosen automatically, however lowering the cpu priority (to 0) will definitely help, but the thing that would help the most in the context gaming is correct cpu affinity (different cores for games and miner), because games tend to use few cores but want them fully.

If you still want to prevent the server from pausing the miner you can compile the miner with the [patch](https://github.com/Bendr0id/xmrigCC/issues/47#issuecomment-368577105) which I posted just few hours before your issue (the coincidence :astonished: )

**Comment by Zelecktor** [comment]
@untoreh Thank you

> The client is currently not able to differentiate between local and remote commands.

This is true, even if i try to pause manually with the keyboard "P", client persist in resume mining.
