### ISSUE TITLE
Request for schedules

### ISSUE THREAD

**Issue by redispade** [Bendr0id/xmrigCC#52]
Hi, would it be technically possible to schedule configurations for clients? For example I want a miner to schedule a worker to use only 1 cpu core during the day, and 4 cpu cores during the night.
Would that be possible in the future releases or it's too much work ? :)

**Comment by Bendr0id** [comment]
With a cronjob, curl and some bash scripting its already possible todo that because XMRigCCServer has an api to do everything you can do on the dashboard via a script.

Find the documentation here:
https://github.com/Bendr0id/xmrigCC/wiki/XMRigCCServer-API

And some samples to start:
https://github.com/Bendr0id/xmrigCC/wiki/Useful-scripts

**Comment by redispade** [comment]
Didn't think of that earlier. Thank you
