### ISSUE TITLE
Two miners on same machine, only one miner can be shown up

### ISSUE THREAD

**Issue by bobbieltd** [Bendr0id/xmrigCC#66]
I run two xmrigDaemon instances on the same machine (Ubuntu 16.04) for two different coins. On control dashboard, there is only one show up (by random. one or another). I guess it's because of duplicate machine name.

**Comment by Bendr0id** [comment]
Yes. The worker name has to be unique. Just manually set a different worker id to solve this problem.

Am 15.03.2018 11:42 schrieb Learner <notifications@github.com>:

I run two xmrigDaemon instances on the same VPS (Ubuntu 16.04) for two different coins. On control dashboard, there is only one show up (by random. one or another). I guess it's because of duplicate machine name.

**Comment by bobbieltd** [comment]
Thank you. Very great software.
