### ISSUE TITLE
optimize miners (xmrigCC) and xmrig-proxy config

### ISSUE THREAD

**Issue by FranzDE** [Bendr0id/xmrigCC#75]
Hi, I'm using xmrigCC miners (about 13 cpu miners and 25 yet to be added) on different networks.
Previously I used for all the xmrig miners, the pool "pool.supportxmr.com:3333" (I know the pool set automatically the most suitable level of difficulty for the single miner)

The hash-power of my 38 miners goes from 60hs (the poorest) to 290hs (the best).
I see that if I don't set "custom-diff": 5000, on xmrig-proxy, all miners take a very high level of difficulty.
After I set "custom-diff": 5000, all miner receve from the xmrig-proxy the difficulty level of 5000.

With "nicehash" support set to "enable" on xmrigCC miner side, I don't see any difference. I read that it should be activated when mining through xmrig-proxy
Or I should use "nicehash" support only with "custom-diff": 0 ??

The actual xmrig-proxy level difficulty receved from pool is 53100.

Since I have miners with different hashpower, what are the optimal settings to adopt? I have noticed that since I have set "custom-diff": 5000 on xmrig-proxy, the "Invalid shares" have drastically decreased.

**Comment by djfinch** [comment]
Hi Frantz,

Well, xmrig-proxy is not able to reduce miner diff. You are probably the best candidate for Snipa's xmr-nodejs-proxy which is able to do it. I'm using it in the same way. CPU #rates varying between 40 to 350.

FiNCh

**Comment by FranzDE** [comment]
I confirm that xmrig-proxy can reduce the miner diff, I can see it directly on xmrigCC logs (miner side). This is the reason the "Invalid shares" have practically disappeared when i set up "custom-diff": 2000

And what about my three questions? :)

**Comment by Bendr0id** [comment]
@FranzDE the diff which is send from pool to the proxy is kind of a mask. The proxy sends every share which passes the mask to the pool. The custom-diff in xmrig-proxy or like it is on xmr-node is just kind of a pseudo diff. 

Lets assume the diff you receive from pool is 20000, but your miner isnt that fast, so it will most potentially take a lot of time until the miner will find a hash which passes the mask. The idea is to send the miner a lower diff that it send more hashes to the proxy (for measuring the miner hash/s i think). But its just pseudo. These shares will be filtered by the proxy (in the case of xmr-node deffinitly) so they wont be rewarded by the pool. The only benefit is that the pool has less load, and you save network traffic.

A 20000 diff share will be rewarded like 10*2000 shares.

Makes sense?

**Comment by Bendr0id** [comment]
2. Nicehash
 -> you have to enable it, nicehash mode is for splitting job.

The pool sends you a job like a range (simple -> mine this range aaaaa:aaaab) and nicehash mode makes it possible that the proxy is able to split that job to n miners.

**Comment by Bendr0id** [comment]
3. Bind
   -> with this option you bind the proxy to an ip:port

If you have multiple network interfaces you can define that it only listens on one of the network interface for example. The port is the listening port

**Comment by Bendr0id** [comment]
4. I'm not the owner of xmrig-proxy :D maybe better ask for these related questions in the right repo.

https://github.com/xmrig/xmrig-proxy

**Comment by djfinch** [comment]
Ah, sorry. It was reaction to very first post...

1. Maybe, but going too much down will result in low-diff shares on the pool and you can be banned. It also increase network communication between pool, proxy and also miners. Snipa's proxy act like a pool on miner side incl vardiff so it will adapt automatically. On pool side is also better leave it on vardiff.  I can make some tests (also running one xmrig-proxy but behind Snipa's proxy which is connected directly to pool).

2. AFAIK xmrig (core) have auto-detect. Latest (2.5.0) also implemented protocol extension to detect proxy. But I'm using it without nicehash option all the time.

3. Address where proxy listening on connections. 0.0.0.0 means all interfaces (even localhost), 127.0.0.1 meas local only  (useful for ssh tunnel, for example). If you have two network cards, you can bind listener to one...

**Comment by FranzDE** [comment]
thank you very much for your answers!
1) So "custom-diff" affects only the communication between the miner and the proxy, not between the miner and the pool.
But using a low "custom-diff" solve my previous "Invalid shares" problems.
Without "custom-diff" 2000 the miners, also the low hash miner (70hs) take 20'000 as difficulty level on miner side.

2) I try to enbale nicehash option on all the miners.

3) If bind 0.0.0.0:3333 accept connection on all ethernets on my proxy, is a good point.


PS: I asked the same questions about the xmrig-proxy github but unfortunately no one answered. Here I found people very helpful and kind ready to help and share information. Thanks again

**Comment by FranzDE** [comment]
Sorry, last doubt...

In my situation, with 38 miners with power that goes from 60hs (the poorest) to 290hs (the best). improves the performance of my mining with a proxy in some way?
The performance of my mining are improved with a proxy? (Ignoring the fact that with a proxy I would overload the pool less.) ...Because I'm getting the doubt that I've put up a proxy that I do not need

**Comment by djfinch** [comment]
1. Nope, its between proxy an pool. Default way from pool to "something" (pool does not know what is on the other side, it should be one high-end miner or proxy) is vardiff. Diff of work pushed to your "something" are adjusted dynamically depending on your hashing power. Following numbers are just example... If you have 2000H/s and vardiff assign you diff.2000, then 50H/s should've got diff.50 but this is bellow minimum diff on most pools (maybe not on really small ones). You will end with low-diff share or pool will send you work which is too hard to compute... So the benefit of proxy is having 10*50H/s miners behind "something" what act like one 500H/s miner. Proxy ask for work, pool will say "hey 500H/s miner, give him diff.500 work" and proxy will divide diff.500 work to miner - diff.50 each. Everything works and you are digging. Not sure how exactly xmrig-proxy works but your situation looks like your proxy getting higher diff then miners can compute and that's probably because proxy cannot lower diff on miner side... Something like: pool sent diff.500, miners got diff.500 and that's above their possibilities. I can't see any fine-tuning there. Snipa's proxy can set miner-side min-diff and max-diff + share-target-time (very useful - work can be divided to even smaller parts), while pool-side can be "fixed-diff" too, but there is no reason for that.

2. Nicehash is mandatory. I just said that it works in my place without explicitly enabling nicehash on my miners. xmrig + xmrig-proxy is somehow compatible so nicehash nonce is properly autodetected almost everytime... But yes, enable it.

3. 0.0.0.0 is good as far as you need to limit listening to interface. Simple example: eth0 - 1.2.3.4 is your public WAN and eth1 - 5.6.7.8 is LAN. Assuming your WAN is not firewalled. What happens if I - nasty guy - start sending thousand of packets to 1.2.3.4:3333?

4. Your 60H/s miners aren't strong enough to submit valid share with minimal diff in target time. Without proxy - they will run in vain or you will be banned.

Consider xmr-nodejs-proxy. That's probably all you need for small miners.

**Here is mine:**
```
1|proxy    | 2018-03-22 20:45 +00:00: Received new block template from communitypool.stellite.cash
1|proxy    | 2018-03-22 20:45 +00:00: The proxy currently has 13 miners connected at 1614 h/s with an average diff of 146
```

**And one of my poorest miner. Everything works well. Notice job diff...**
```
[2018-03-22 21:42:10] new job from 192.168.20.214:9999 diff 100
[2018-03-22 21:42:10] accepted (162460/0) diff 100 (427 ms)
[2018-03-22 21:42:11] accepted (162461/0) diff 100 (430 ms)
[2018-03-22 21:42:11] accepted (162462/0) diff 100 (402 ms)
[2018-03-22 21:42:11] accepted (162463/0) diff 100 (121 ms)
[2018-03-22 21:42:11] accepted (162464/0) diff 100 (112 ms)
[2018-03-22 21:42:17] accepted (162465/0) diff 100 (5585 ms)
[2018-03-22 21:42:18] accepted (162466/0) diff 100 (697 ms)
[2018-03-22 21:42:18] accepted (162467/0) diff 100 (116 ms)
[2018-03-22 21:42:18] accepted (162468/0) diff 100 (185 ms)
[2018-03-22 21:42:21] accepted (162469/0) diff 100 (2598 ms)
[2018-03-22 21:42:21] accepted (162470/0) diff 100 (63 ms)
[2018-03-22 21:42:21] speed 2.5s/60s/15m 61.5 62.4 62.9 H/s max: 66.4 H/s
```

**Comment by FranzDE** [comment]
**@djfinc**h Thanks for your reply, I have installed xmr-node-proxy and changed the resolve of my recordA to point all (13 test) miners on the new proxy. The hashrate shown by the proxy is much more constant than that indicated by xmrig-proxy

![xmr-node-proxy](https://user-images.githubusercontent.com/37615468/37805131-89ba9544-2e38-11e8-98a7-d90316e3da95.jpg)

```
{
  "pools": [
    {
      "hostname": "pool.supportxmr.com",
      "port": 3333,
      "ssl": false,
      "allowSelfSignedSSL": false,
      "share": 100,
      "username": "[wallet]",
      "password": "xmr-node-proxy",
      "keepAlive": true,
      "coin": "xmr",
      "default": true
    }
  ],
  "listeningPorts": [
    {
      "port": 3333,
      "ssl": false,
      "diff": 2500,
      "coin": "xmr"
    }
  ],
  "bindAddress": "0.0.0.0",
  "developerShare": 1,
  "daemonAddress": "127.0.0.1:18081",
  "coinSettings": {
    "xmr":{
      "minDiff": 100,
      "maxDiff": 300000,
      "shareTargetTime": 5
    }
  }
}
```

I know this is not the best place to ask it, (sorry) but can I integrate a web interface (API) to manage the proxy?

on xmrig-proxy I use the service "Local Proxy Stat":
![xmrig-proxy - copia](https://user-images.githubusercontent.com/37615468/37805288-7109f412-2e39-11e8-80e3-8649cfca1104.PNG)
(paying no attention to "invalid shares" was the first configuration with xmrig-proxy without "custom-diff".)

**Comment by sebastianstolzenberg** [comment]
No idea what's causing your invalid shares. Probably the jobs where outdated at the time the miners sent their result. But since you seem to be loosing 10%, I would bother. Have you checked the report on the pool's dashboard? Is it showing the same rate?

I doubt that the effective hash rates differ between the xmr-nodejs-proxy and xmrig-proxy. The averages are just calculated with different time windows. Still I'd also prefer the way xmr-nodejs-proxy splits the jobs over the nice hashing used by xmrig-proxy. But then xmr-nodejs-proxy can only handle nodejs-pools, while xmrig-proxy is compatible to more.
Btw. I'm currently working on a new proxy implementation which combines both approaches. It will automatically chooses best job breakdown approach suitable to both pool and miner. Maybe you could give it a try once it's ready: 
[https://github.com/sebastianstolzenberg/ses_proxy](url) 
... the name still has to change. though.

**Comment by FranzDE** [comment]
These are the tests I conducted this night with 13 miners on Snipa22/xmr-node-proxy
Zero invalid shares
Stats from the pool ( I would say that it is quite linear, with few oscillations. when I was without Snipas proxy the values had much stronger oscillations)
![xmr-node-proxy](https://user-images.githubusercontent.com/37615468/37828055-0d114c60-2e9a-11e8-8265-a2ec0604533b.png)

**Comment by FranzDE** [comment]
Now I started testing with my 13 miner the [JerryWm / Stratum-Proxy-XMR](https://github.com/JerryWm/Stratum-Proxy-XMR)
It has an atypical web interface, but when it comes to confidence it is very complete and detailed.
I found it quite unknown on the internet, but it seems to work really well.
This night I tried it with just one miner, and recently I moved my other 12 test miners on it.

![jerrywm_stratum-proxy-xmr](https://user-images.githubusercontent.com/37615468/37828528-e68c9a02-2e9b-11e8-9ec2-8d174afac8ed.png)

![jerrywm_stratum-proxy-xmr_active-jobs](https://user-images.githubusercontent.com/37615468/37828611-4725da7c-2e9c-11e8-91e0-d26d944da03c.png)

![jerrywm_stratum-proxy-xmr_shares](https://user-images.githubusercontent.com/37615468/37828740-bfe22e48-2e9c-11e8-82b2-606e55729310.png)

REAL TIME CONSOLE
![jerrywm_stratum-proxy-xmr_console](https://user-images.githubusercontent.com/37615468/37828838-10e1c844-2e9d-11e8-9ff9-8f476aa08ad1.png)

On settings page it can only manage, pools.
Tuning settings must be done on config.json

```
{
	
	stratum_servers: [
	
		{
			bind_address: "0.0.0.0:5555",
			share_time: 10,
			start_difficulty: 1000,
			min_difficulty: 10,
			ssl: false,
		},
	],
	
	web_server: {
		//	enable
		enable: true,
		
		//	bind web server address
		bind_address: "0.0.0.0:8000",
		
		//	secret key
		auth_key: "PASSWORD",
		
		// open browser
		open_browser: false,
	},

}
```

I will let you know the results of my test so you can have a comparison

**Comment by FranzDE** [comment]
Hi guys, sorry for the delay in my answer.
These are the statistics using JerryWm_Stratum-Proxy-XMR

directly from the pool
![stratum-proxy-xmr_mining jpg](https://user-images.githubusercontent.com/37615468/37895545-e6428dac-30e1-11e8-9590-d2c5bf6d79ed.jpg)

stats from serverCC
![stratum-proxy-xmr_cclog](https://user-images.githubusercontent.com/37615468/37896714-b4a279a8-30e4-11e8-8790-492a2ea9a85c.png)

**Comment by FranzDE** [comment]
These are the statistics using snipa xmr-node-proxy
![snipa_mining](https://user-images.githubusercontent.com/37615468/37896963-558c325a-30e5-11e8-8676-2dc64d1c9c6c.png)

stats from serverCC
![snipa_cc](https://user-images.githubusercontent.com/37615468/37897150-c645cccc-30e5-11e8-9846-23e011e8d826.png)
