### ISSUE TITLE
CC server crash linux

### ISSUE THREAD

**Issue by redispade** [Bendr0id/xmrigCC#76]
I enabled TLS on my testserver 2 days ago and I found it crashed today with this log:

xmrigCCServer: src/unix/fs.c:937: uv__fs_done: Assertion `(((const QUEUE *) (&(req->loop)->active_reqs) == (const QUEUE *) (*(QUEUE **) &((*(&(req->loop)->active_reqs))[0]))) == 0)' failed

Non TLS server running without issues(1.5.1 both versions)

**Comment by Bendr0id** [comment]
Hmm.. I'm using TLS since 1.5.0 without any issues and restart of the server. There error doesn't look like a TLS or network error.. Does it happen once, or are you able to reproduce?



Am 25.03.2018 13:18 schrieb redispade <notifications@github.com>:

I enabled TLS on my testserver 2 days ago and I found it crashed today with this log:

xmrigCCServer: src/unix/fs.c:937: uv__fs_done: Assertion `(((const QUEUE ) (&(req->loop)->active_reqs) == (const QUEUE ) ((QUEUE **) &(((&(req->loop)->active_reqs))[0]))) == 0)' failed

Non TLS server running without issues(1.5.1 both versions)

**Comment by redispade** [comment]
Actually it has crashed several times but this was the first time it got a log. I will try to run it with gdb and see what I get out of it

**Comment by redispade** [comment]
I am running a bash script to relaunch it on crash up to 15 times, and it has crashed 15 times in 2 days. The clients are all 1.5.1 with tls enabled.

**Comment by Bendr0id** [comment]
CoreDump would be very helpfull.How much clients you have connected..? How much RAM is available..? Need some more infos about the Server.

**Comment by serialzs** [comment]
even without tls it crashes..even i trigger the restart, pause & start..it stay to 0 hashrate..may i request to fork v2.5.1..thanks..

**Comment by Bendr0id** [comment]
@serialzs what is the connection between your miner issue and the server crash. I don't get it. 0 hashrate in dashboard could have multiple issues. For example very slow miners, wrong algo in config. That isn't a general issue. A lot of ppl. already using 1.5.2 for testing before I released it, without any issues.

Be more clear, what crashes, what is with the trigger and why should I fork 2.5.1? 1.5.2 already contains most of 2.5.1 except the new proxy protocol.

**Comment by redispade** [comment]
Since I upgraded to 1.5.2 it did not crash anymore... still testing it.

**Comment by Bendr0id** [comment]
O_o no idea why. I can't get a clue out of this whole issue.

**Comment by Bendr0id** [comment]
@serialzs please create separate ticket with more info. 

Os, cpu's,  aes .. put as much info  as possible. 

Only saying doesn't work, doesn't help.

**Comment by redispade** [comment]
I migrated all my miners to 1.5.2 ssl and it has been 27 hours up and running with no issues. I confirm this is not an issue anymore :)
