### ISSUE TITLE
xmrigDaemon function: reboot xmrigMiner

### ISSUE THREAD

**Issue by FranzDE** [Bendr0id/xmrigCC#85]
Hi guys!

> New changelog: 1.5.5
> * Added restart of crashed miners to xmrigDaemon

this is the code I used as a personal "loader":
```
@echo off
:Restart
start "xmrigMiner" /wait "C:\path_to_miner_folder\xmrigMiner.exe" --daemonized
TIMEOUT 60
goto Restart
```

Is it possible to customize the restart, with a timeout like I did in my code? (timeut 60 seconds)
Regards

**Comment by Bendr0id** [comment]
https://github.com/Bendr0id/xmrigCC/blob/master/src/cc/XMRigd.cpp

std::this_thread::sleep_for(std::chrono::milliseconds(1000));

Replace with your timeout.

**Comment by FranzDE** [comment]
perfect, thanks!

**Comment by FranzDE** [comment]
I tested the “reload” function and it is not working.
If I kill the Miner from win10 taskmanager, the Loader does not reload it.

Maybe your reload works differently and I misunderstood?

**Comment by Bendr0id** [comment]
Hi,
Yes it seems that you misunderstood that feauter. It restarts the miner to apply config changes and also of the miner crash's. When you explicitly kill it from the Taskmanager the whole process and it's child's will die, so the daemon can't restart it because it also dies.

On linux it works, that you can kill the client process, but on windows it doesn't do it.

Am 03.04.2018 20:02 schrieb FranzDE <notifications@github.com>:

I tested the “reload” function and it is not working.
If I kill the Miner from win10 taskmanager, the Loader does not reload it.

Maybe your reload works differently and I misunderstood?

**Comment by FranzDE** [comment]
ok, thanks for the clarification
