### ISSUE TITLE
background option (-B) disabled on pre-compiled version

### ISSUE THREAD

**Issue by syrius01** [Bendr0id/xmrigCC#89]
Hi !

I really like this miner, especially the pre-compiled version which saves me from some headaches of compiling the miner. The only issue I'm having is that the background option (-B) is disabled on the pre-compiled version. I was wondering if it could be possible to release a pre-compiled version with the background option available?

Thanks!

**Comment by FranzDE** [comment]
You have to enable it in the “config.json” file.

**Comment by syrius01** [comment]
No unfortunately this will not fix it with the pre-compiled version FranzDE since it's disabled.

**Comment by Bendr0id** [comment]
It's disabled because it doesn't work on linux. It only works on windows in a proper way. Use screen or termux or a systemd service to achieve that.

Am 17.04.2018 18:26 schrieb syrius01 <notifications@github.com>:

No unfortunately this will not fix it with the pre-compiled version FranzDE since it's disabled.
